name: user_adelle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cherry_toast: ^1.12.0
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.4
  flutter_neat_and_clean_calendar: ^0.4.16
  google_fonts: ^6.2.1
  intl: ^0.19.0
  scrollable_clean_calendar: ^1.5.0
  supabase_flutter: ^2.8.3
  syncfusion_flutter_gauges: ^28.2.4
  table_calendar: ^3.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
