name: user_adelle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  android_alarm_manager_plus: ^4.0.7
  cherry_toast: ^1.12.0
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.4
  flutter_local_notifications: ^19.1.0
  flutter_neat_and_clean_calendar: ^0.4.16
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.0+1
  scrollable_clean_calendar: ^1.5.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.8.3
  syncfusion_flutter_gauges: ^28.2.4
  table_calendar: ^3.1.3
  timezone: ^0.10.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
