name: admin_adelle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  
  cherry_toast: ^1.12.0
  
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.2
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  pie_chart: ^5.4.0
  provider: ^6.1.2
  supabase_flutter: ^2.8.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  
  
